### ISSUE TITLE
Duvida Desafio 6

### ISSUE THREAD

**Issue by Caciquez** [tryber/sd-05-mongodb-commerce#10]
> Desafio 6
> Inclua bacon no final da lista de ingredientes dos sanduíches Big Mac e Quarteirão com Queijo.
> 
> Para isso, escreva no arquivo desafio6.js duas queries, nesta ordem:
> 
> Crie uma query que faça a inclusão de bacon no final da lista de ingredientes dos sanduíches Big Mac e Quarteirão com Queijo.
> 
> Crie uma query que retorne o nome e ingredientes de todos os documentos.

Na descrição do requisito, não entendi se o texto a ser buscado deve ser considerado como lowercase ou uppercase ?

**Comment by Caciquez** [comment]
@kylefelipe vi você teve o mesmo problema encontrou alguma solução ?

**Comment by Andrevlc** [comment]
A sua dúvida é na pesquisa ou na inserção ?

**Comment by Caciquez** [comment]
Então estou na duvida no caso de quando for realizar uma pesquisa usando o comando de **find()**

```javascript
db.collection.find()
```

**Comment by Caciquez** [comment]
@tryber/students-sd-05 Alooo meu povo

**Comment by kylefelipe** [comment]
Deu ruimmm.. não vai pra todo mundo não
