### ISSUE TITLE
Dúvidas no desafio 5

### ISSUE THREAD

**Issue by hleoc** [tryber/sd-05-mongodb-commerce#28]
Desafio 5
Adicione ketchup aos ingredientes para todos os sanduíches menos o McChicken, garantindo que não haja duplicidade nos ingredientes.

Mas observando a base de dados verifiquei que o sanduíche que possui ketchup no campo ingrediente é o Quarteirão com Queijo e NÃO o McChicken.

**Comment by Caciquez** [comment]
Opa @hleoc !

A ideia no caso é que você deve atualizar adicionando o ingrediente de ketchup a todos os sanduíches que não sejam **McChicken**.  Sendo assim ignorar no seu **update** qualquer sanduíche que seja **McChicken**, e caso o sanduiche seja um **Quarteirão**, que já tenha ketchup você não deve adicionar novamente a ele.

 Faz sentido ?

**Comment by mjgargani** [comment]
Encerrando a issue, caso alguma dúvida adicional é abrir uma nova ;)
